[package]
name = "rax-core"
version = "0.4.3"
edition = "2021"

[dependencies]
cap-fs-ext = "4.0.2"
cap-std = "4.0.2"
fs2 = "0.4.3"
libc = "0.2.177"
memmap2 = "0.9.9"
sha2 = "0.10.9"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile = "3.23.0"
