[package]
name = "rax-runtime"
version = "0.4.1"
edition = "2021"

[dependencies]
libc = "0.2.177"
serde_json = "1.0.145"
rax-bench-model = { path = "../rax-bench-model" }
rax-core = { path = "../rax-core" }
rax-docstore = { path = "../rax-docstore" }
rax-search = { path = "../rax-search" }
rax-text = { path = "../rax-text" }
rax-vector = { path = "../rax-vector" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile = "3.23.0"
rax-bench-packer = { path = "../rax-bench-packer" }
rax-text = { path = "../rax-text" }
rax-vector = { path = "../rax-vector" }
